### ISSUE TITLE
var and var-file options to validate action

### ISSUE THREAD

**Issue by yogeshlonkar** [jmccann/drone-terraform#108]
```yaml
  image: jmccann/drone-terraform:6.1-0.12.11
  root_dir: terraform
  var_files: terraform.tfvars
  vars:
    xyz: "abc"
  actions:
    - validate
```
Above step generates below warning
```
Warning: The -var and -var-file flags are not used in validate. Setting them has no effect.
```
Can `-var` and `-var-file` not passed in `validate` action?
