### ISSUE TITLE
Is this project still active? - Using env-vars in vars

### ISSUE THREAD

**Issue by unfor19** [jmccann/drone-terraform#117]
Is this project still active? I have a few enhancements that I've added here - https://github.com/unfor19/drone-terraform

I would really like to push it to this project to avoid duplicate work.

**Comment by unfor19** [comment]
@jmccann ?

**Comment by caioquirino** [comment]
@unfor19 Yes, the project is still active :) 
What are the enhancements you are thinking that could be beneficial to the project?

**Comment by jmccann** [comment]
It's still active in the sense that I work to maintain it by reviewing PRs and such.  I don't so much actively try to develop it as I don't use it much myself anymore.  Plus there may be other better tools to do automation against TF now such as https://www.runatlantis.io/guide/#getting-started

Totally open to reviewing any potential PRs you'd like to open.  Will say that:

* more smaller and more focused PRs preferred vs 1 big PR with all your updates
* unit testing helps PRs get reviewed and merged

**Comment by unfor19** [comment]
@jmccann @caioquirino Thanks for reaching out!
The PR that I want to push - allow the use of environment variables in `vars`, for example:

`drone.yml`
```yml
  - name: server-terraform
    when:
      branch:
        - dev
        - staging
    image: unfor19/drone-terraform:dev
    pull: "always"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id_dev
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key_dev
      DB_MASTER_PASSWORD:
        from_secret: hm_server_${DRONE_BRANCH}_db_password # <-- set as env var
    settings:
      actions:
        - validate
        - plan
        - apply
      root_dir: ${DRONE_BRANCH}/server
      vars:
        server_image_tag_latest: drone-latest
        environment: ${DRONE_BRANCH}
        db_master_password: $${DB_MASTER_PASSWORD} # <-- using the env var, note the double $$
```

The rest of the changes that I made are negligible, but I do think that this one is a great improvement. I've already set up this feature for one of my customers, and it works great.

Do you want me to push this PR?
