### ISSUE TITLE
Is there a way to specify terraform workspace?

### ISSUE THREAD

**Issue by sneas** [jmccann/drone-terraform#126]
Hi @jmccann, thank you for this plugin. I'm a bit puzzled with specifying a workspace used by terraform. Is there any way to do that?

**Comment by sneas** [comment]
For the record, this could be done without the plugin:

```yaml
steps:
  - name: deploy
    image: hashicorp/terraform:light
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - terraform init
      - terraform workspace select workspace-name
      - terraform plan
      - terraform apply -auto-approve
```
