### ISSUE TITLE
How should the plugin/workflow handle 'terraform delete'?

### ISSUE THREAD

**Issue by flyinprogrammer** [jmccann/drone-terraform#13]
So the obvious workflow of branches should run terraform plan, and a merge to master might run terraform apply seems obvious to me.

But at the end of the day when I want to use terraform to spin my things down, how should that be accomplished?

If we figure this out I'll get this plugin a PR for delete support ?

**Comment by as0bu** [comment]
@flyinprogrammer I was thinking about this myself. I think that by default it should destroy the environment on a successful deployment, leave it up on failure, and then also have an option to not destroy via the .drone.yml. That's my two cents.

**Comment by Drc0w** [comment]
Hey there, I think that it could be useful to tell the plugin which command(s) has(have) to run after a plan. For example, I would like to bring a platform up, then provision it and finally destroy it. Maybe, it would be possible to specify multiple commands to run.

The use of the plugin could look like this:

```
pipeline:
  terraform:
    image: jmccann/drone-terraform
    plan: false
    command: ["apply", "destroy"]
    [...]
```

Or in the case we want to use a single command:

```
pipeline:
  terraform:
    image: jmccann/drone-terraform
    plan: false
    command: apply
    [...]
```

What do you guys think?
