### ISSUE TITLE
not able to get root_dir working

### ISSUE THREAD

**Issue by aswinvg** [jmccann/drone-terraform#45]
trying to use root_dir and the set the directory to run the terraform commands.

But it does not work - even though others in the pipeline mentioned in drone work which does not have root dir.. 
Root Dir is a directory called dir1 within a git repo.

Wondering whats being missed..

Example drone yml
```
pipeline:
  plan-1:
    image: "jmccann/drone-terraform:latest"
    plan: true
    pull: true
    sensitive: true
    remote:
        backend: consul
        config:
          path: "folder/key"
          address: "ip:8500"
    vars:
        .......
        .......
  plan-2:
    image: "jmccann/drone-terraform:latest"
    plan: true
    pull: true
    root_dir: dir1
    sensitive: false
    vars: 
        .....
        .....
```

Wondering what am i missing here. Appreciate your help.
