### ISSUE TITLE
Fetching private modules over HTTPS

### ISSUE THREAD

**Issue by arkan** [jmccann/drone-terraform#59]
Hello,

I'm trying to use a private module hosted on Github without success. 
```
module "my-module" {
  source = "github.com/my_org/my_repo/my_module/"
}
```

And the output is 
```
Get: git::https://github.com/my_org/my_repo.git
Error downloading modules: Error loading modules: error downloading 'https://github.com/my_org/my_repo.git': /usr/bin/git exited with 128: Cloning into '.terraform/modules/f57680d92dfe982c5f1a6b477391e0bb'...
fatal: could not read Username for 'https://github.com': No such device or address
```

I read https://github.com/jmccann/drone-terraform/issues/42 and http://readme.drone.io/questions/how-to-clone-private-deps/ but still don't understand why my build fails. 

Any idea?

**Comment by jbfarez** [comment]
Yeah it would be good to have some clues @jmccann 😃

**Comment by msuterski** [comment]
This does not look like an error from drone or a plugin, but rather terraform itself.

Terraform needs to be able to access your private modules. Are you setting the plugin's env so that TF can access your private repo?

**Comment by arkan** [comment]
> Are you setting the plugin's env so that TF can access your private repo?

What do you exactly mean @msuterski ? 

The configuration I use is pretty basic:
```
  plan:
    image: jmccann/drone-terraform:latest
    tf_version: 0.10.7
    plan: true
    root_dir: terraform/eu-west-1
    secrets:
      - source: AWS_ROLE_TO_ASSUME
        target: PLUGIN_ROLE_ARN_TO_ASSUME
    environment:
      - AWS_REGION=eu-west-1
    when:
      event: pull_request
```

And I missing something?
