### ISSUE TITLE
Unused root_dir config option

### ISSUE THREAD

**Issue by roobert** [jmccann/drone-terraform#64]
Thanks for the great plugin!

Unless I'm missing something the `root_dir` parameter isn't honoured.

I'll have a look at fixing this tomorrow if it hasn't been picked up.

**Comment by jmccann** [comment]
I've used it fine.  Referenced in code @ https://github.com/jmccann/drone-terraform/blob/81e17a43399ec6274180a38fad1304fc1eda7009/plugin.go#L120-L122

Gonna close this for now ... if you get more details or need help feel free to re-open.

**Comment by roobert** [comment]
Hi jmccann, I Can't seem to get this to work (assuming my config is in the `terraform` dir relative to repository root). My config:
```
  validate:
    image: jmccann/drone-terraform:5.0
    terraform:
      root_dir: terraform
      actions:
        - validate
```
error:
```
Error loading configuration: No Terraform configuration files found in directory: /drone/src/github.com/<org>/<repo>
```

**Comment by jmccann** [comment]
maybe try

```yaml
pipeline:
  validate:
    image: jmccann/drone-terraform:5.0
    root_dir: terraform
    actions:
      - validate
```
