### ISSUE TITLE
Unable to pass a secret

### ISSUE THREAD

**Issue by nodefortytwo** [jmccann/drone-terraform#70]
I have the following pipeline:

```
pipeline:
  plan:
    group: plan
    image: jmccann/drone-terraform:5
    role_arn_to_assume: arn:aws:iam::157693190368:role/automation-drone
    secrets:
      github_token: GITHUB_TOKEN
    actions:
      - validate
      - plan
    when:
      event: push
```
And i get the following error output

```
yaml: unmarshal errors: line 5: cannot unmarshal !!map into []*yaml.Secret
```
