### ISSUE TITLE
Error: Required variable not set

### ISSUE THREAD

**Issue by ilianamarcano** [jmccann/drone-terraform#72]
Error: Required variable not set: dbpass

Error: Required variable not set: dblogin

Config

  ```
build-tf-staging:
      image: jmccann/drone-terraform:5.0-0.11.7
      actions:
        - validate
        - plan
        - apply
      sensitive: true
      root_dir: terraform
      init_options:
        backend-config:
          - "scheme=http"
          - "path=amida-api/staging/terraform-state"
          - "datacenter=south_central_us"
      vars:
        resource_group_name: xxxxxx
        environment: staging
      secrets:
        - source: db_login
          target: dblogin
        - source: db_pass
          target: dbpass
```

**Comment by appleboy** [comment]
See https://github.com/jmccann/drone-terraform/pull/71

**Comment by jmccann** [comment]
To pass vars into terraform you need to prefix the envvar used with `tf_var_` ... so I think your example fixed would look something like:

```
build-tf-staging:
    image: jmccann/drone-terraform:5.0-0.11.7
    actions:
      - validate
      - plan
      - apply
    sensitive: true
    root_dir: terraform
    init_options:
      backend-config:
        - "scheme=http"
        - "path=amida-api/staging/terraform-state"
        - "datacenter=south_central_us"
    vars:
      resource_group_name: xxxxxx
      environment: staging
    secrets:
      - source: db_login
        target: tf_var_dblogin
      - source: db_pass
        target: tf_var_dbpass
```

Feel free to reopen if this doesn't help or I misunderstood the issue.
