### ISSUE TITLE
Support GCP service accounts

### ISSUE THREAD

**Issue by luis-silva** [jmccann/drone-terraform#89]
@jmccann 
I use this plugin heavily for AWS resources and I am considering my options and evaluating if I could continue to use it for GCP resources as well. Since it already supports the AWS assume role functionality, would you be open to a PR to support GCP service accounts too?

In theory, the plugin should be provider agnostic since this is a terraform plugin, but it already has support for AWS roles so it wouldn't break the pattern if I added the support for GCP service accounts as well.

If you're happy with it and I decide this is the way I want to go I can work on a PR.

**Comment by jmccann** [comment]
So I think that stuff is before my time.  I think your use case in context of entire Drone pipeline is valid.  Also not sure if it should be directly supported by this plugin.

I wonder if you could perform your GCP auth in a previous step and write the creds to an `env-file` that is then loaded via this plugin: https://github.com/jmccann/drone-terraform/blob/master/main.go#L37-L40

Based off the AWS code in this plugin, would be something like

```
pipeline:
  aws-auth:
    image: ...
    commands:
      - some command to perform auth
      - write auth to file > terraform.env-file

  terraform:
    image: jmccann/drone-terraform
    env-file: terraform.env-file
```

`terraform.env-file`:
```
AWS_ACCESS_KEY_ID=abcd123
AWS_SECRET_ACCESS_KEY=abcd123
AWS_SESSION_TOKEN=abcd123
```

**Comment by msuterski** [comment]
The TF's GCP provider already supports SA credentials through the `GOOGLE_CREDENTIALS` env var.

More details here https://www.terraform.io/docs/providers/google/provider_reference.html#full-reference

An example

```
pipeline:
  syntax_check:
    image: jmccann/drone-terraform:5
    actions:
      - validate
    secrets:
      - source: AUTOMATION_GOOGLE_CREDENTIALS
        target: GOOGLE_CREDENTIALS
    when:
      event: [push, pull_request]
```
